# Generated by Django 5.2.17 on 2026-09-25 13:50

from django.db import migrations, models


# The only names the old geocoding could have stored in practice
# (Nantes-focused testing); anything else is cleared.
KNOWN_COUNTRIES = {"France": "FR", "Belgique": "BE", "Belgium": "BE"}


def clear_country_names(apps, schema_editor):
    """Country names can't fit the new 2-letter code column.

    Convert the known ones, clear the rest rather than fail. Only development databases can hold
    any (no production data existed when this ran); such locations
    are simply left without a country.
    """
    Location = apps.get_model("core", "Location")
    for name, code in KNOWN_COUNTRIES.items():
        Location.objects.filter(country=name).update(country=code)
    Location.objects.filter(country__regex=r"^.{3,}$").update(country="")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(clear_country_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
