# Generated by Django 5.2.17 on 2026-09-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_location_country"),
    ]

    # Browsing (mobilito_app.browse) filters and snaps points as
    # planar geometry (a map viewport is a lat/lon rectangle), which
    # the geography column's own index can't serve.
    operations = [
        migrations.RunSQL(
            "CREATE INDEX core_location_point_geom_idx "
            "ON core_location USING GIST ((point::geometry));",
            "DROP INDEX core_location_point_geom_idx;",
        ),
    ]
