# Generated by Django 5.2.17 on 2026-08-29 16:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InfrastructureTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("label_fr", models.CharField(max_length=100, null=True)),
                ("label_en", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(blank=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2 code. Blank means universal.",
                        max_length=2,
                    ),
                ),
                ("family", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deprecated", "Deprecated")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=2)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("commune", models.CharField(blank=True, max_length=100)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[("email", "Email")], default="email", max_length=20
                    ),
                ),
                ("contact_value", models.CharField(max_length=255)),
                ("do_not_contact", models.BooleanField(default=False)),
                ("display_guidance", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfrastructureObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("pending_validation", "Pending validation"),
                            ("pending_moderation", "Pending moderation"),
                            ("published", "Published"),
                            ("light_hold", "Light hold"),
                            ("sandboxed", "Sandboxed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "observer_perspective",
                    models.CharField(
                        choices=[
                            ("ped", "Pedestrian"),
                            ("bike", "Cyclist"),
                            ("both", "Both"),
                        ],
                        max_length=4,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "moderation_state",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("cleared", "Cleared"),
                            ("flagged", "Flagged for review"),
                        ],
                        default="unreviewed",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="core.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InfrastructureMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo")], default="photo", max_length=10
                    ),
                ),
                ("file", models.ImageField(upload_to="infrastructure_media/%Y/%m/")),
                (
                    "exif_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "moderation_state",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("cleared", "Cleared"),
                            ("flagged", "Flagged for review"),
                        ],
                        default="unreviewed",
                        max_length=20,
                    ),
                ),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infrastructure_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="mobilito_app.infrastructureobservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModalShareSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("pending_validation", "Pending validation"),
                            ("pending_moderation", "Pending moderation"),
                            ("published", "Published"),
                            ("light_hold", "Light hold"),
                            ("sandboxed", "Sandboxed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_pedestrian", models.PositiveIntegerField(default=0)),
                ("total_cyclist", models.PositiveIntegerField(default=0)),
                ("total_car", models.PositiveIntegerField(default=0)),
                ("total_tc", models.PositiveIntegerField(default=0)),
                ("integrity_hash", models.CharField(blank=True, max_length=64)),
                ("location_mismatch", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="core.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ObservationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("me_too", "Me too"),
                            ("progress", "Progress"),
                            ("degradation", "Degradation"),
                            ("resolved", "Resolved"),
                            ("additional_issue", "Additional issue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observation_actions",
                        to="mobilito_app.infrastructuremedia",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="mobilito_app.infrastructureobservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModalShareCountEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ped", "Pedestrian"),
                            ("bike", "Cyclist"),
                            ("car", "Car"),
                            ("tc", "Public transit"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="mobilito_app.modalsharesession",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session", "timestamp"],
                        name="mobilito_ap_session_fbea37_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModerationFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("inappropriate", "Inappropriate"),
                            ("spam", "Spam"),
                            ("off_topic", "Off-topic"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="mobilito_ap_content_88cda6_idx",
                    )
                ],
            },
        ),
    ]
