# Generated by Django 5.2.17 on 2026-09-25 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_signinattempt"),
        ("mobilito_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructureobservation",
            name="sign_in_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="authentication.signinattempt",
            ),
        ),
        migrations.AddField(
            model_name="modalsharesession",
            name="sign_in_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="authentication.signinattempt",
            ),
        ),
    ]
