# Generated by Django 5.2.17 on 2026-09-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobilito_app", "0002_infrastructureobservation_sign_in_attempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modalsharecountevent",
            name="client_event_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="modalsharecountevent",
            constraint=models.UniqueConstraint(
                fields=("session", "client_event_id"),
                name="unique_client_event_per_session",
            ),
        ),
    ]
