# Generated by Django 5.2.17 on 2026-09-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobilito_app", "0003_modalsharecountevent_client_event_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructureobservation",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="observations",
                to="mobilito_app.infrastructuretag",
            ),
        ),
    ]
