# Generated by Django 5.2.17 on 2026-09-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobilito_app", "0004_infrastructureobservation_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructureobservation",
            name="client_submission_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
