# Generated by Django 5.2.17 on 2026-09-30 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobilito_app",
            "0005_infrastructureobservation_client_submission_id",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationflag",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moderationflag",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_moderation_flags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="moderationflag",
            name="reason",
            field=models.CharField(
                choices=[
                    ("inappropriate", "Inappropriate"),
                    ("privacy", "Personal information"),
                    ("spam", "Spam"),
                    ("off_topic", "Off-topic"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
