# Generated by Django 5.2.17 on 2026-08-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilitouser",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[("fr", "Français"), ("en", "English")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mobilitouser",
            name="use_device_location",
            field=models.BooleanField(default=True),
        ),
    ]
