# Generated by Django 5.2.17 on 2026-09-25 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_mobilitouser_preferred_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignInAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_user", models.BooleanField(default=False)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("reminders_sent", models.PositiveSmallIntegerField(default=0)),
                ("last_reminded_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sign_in_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["confirmed_at", "created_at"],
                        name="authenticat_confirm_e027e3_idx",
                    )
                ],
            },
        ),
    ]
