name: JavaScript Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-26.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test-js
